# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to ~/.config/fish/completions/wb-mqtt-db-cli.fish
# 2) Ensure a binary named wb-mqtt-db-cli is in your PATH
# See also: https://fishshell.com/docs/current/completions.html#where-to-put-completions


# Parse current commandline:
# - _shtab_wb_common_cmdpath=(sub)command path seen so far
# - _shtab_wb_common_npos=number of positional arguments given after it
# - options are skipped based on _shtab_wb_common_opts_with_value & _shtab_wb_common_commands lists
function _shtab_wb_common_scan
  set -g _shtab_wb_common_cmdpath ''
  set -g _shtab_wb_common_npos 0
  set -l tokens (commandline -opc)
  set -e tokens[1]
  set -l expect_value 0
  for t in $tokens
    if test $expect_value -eq 1
      set expect_value 0
      continue
    end
    switch "$t"
      case '--*=*'
        continue
      case '-*'
        if contains -- $t $_shtab_wb_common_opts_with_value
          set expect_value 1
        end
        continue
      case '*'
        if test $_shtab_wb_common_npos -eq 0
          set -l candidate $t
          if test -n "$_shtab_wb_common_cmdpath"
            set candidate "$_shtab_wb_common_cmdpath $t"
          end
          if contains -- $candidate $_shtab_wb_common_commands
            set -g _shtab_wb_common_cmdpath $candidate
            continue
          end
        end
        set -g _shtab_wb_common_npos (math $_shtab_wb_common_npos + 1)
    end
  end
end

# Condition helper: true if the current (sub)command path equals the given one.
function _shtab_wb_common_using
  _shtab_wb_common_scan
  test "$_shtab_wb_common_cmdpath" = "$argv"
end

set -g _shtab_wb_common_commands 
set -g _shtab_wb_common_opts_with_value --broker --decimal-places --delimiter --from --interval --limit --max-records --output-fname --time-format --timeout --to -b -d -o

complete -c wb-mqtt-db-cli -e
complete -c wb-mqtt-db-cli -f

complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -l help -d 'show this help message and exit'
complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -s b -l broker -x -d 'MQTT broker url (default: unix:///var/run/mosquitto/mosquitto.sock)'
complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -l from -x -d 'start date (default: None)'
complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -l to -x -d 'end date (default: None)'
complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -l time-format -x -d 'strftime-style format string for timestamp formating. Use "%s.%f" for UNIX timestamp (default: %Y-%m-%d %H:%M:%S.%f)'
complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -l limit -x -d 'The maximum number of data points to request (default: 10000)'
complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -l interval -x -d 'Min interval between data points (ms) (default: None)'
complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -s a -l auto-interval -d 'Automatically estimate the interval between data points based on "limit", "from" and "start" (default: False)'
complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -l max-records -x -d 'Max number of records within interval (default: None)'
complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -l decimal-places -x -d 'Number of decimal places in value (default: None)'
complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -s d -l delimiter -x -d 'CSV field separator (default: )'
complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -s o -l output-fname -x -d 'Write result to file. "-" means stdout (default: -)'
complete -c wb-mqtt-db-cli -n _shtab_wb_common_using -l timeout -x -d 'Request timeout (in seconds) (default: None)'

